name: Github actions validation sass

on:
  workflow_call:

jobs:
  Stylelint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: 'npm'
      - name: NPM dependencies
        run: npm ci
      - name: Stylelint validation
        run: npm run stylelint